# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: pip install -r requirements.txt
    command: streamlit run Hello.py

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 8501 for the frontend
    port: 8501
    onOpen: open-preview
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
